apiVersion: apps/v1
kind: Deployment
metadata:
  name: code-execution-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: code-execution-api
  template:
    metadata:
      labels:
        app: code-execution-api
    spec:
      containers:
      - name: api
        image: code-execution-api:latest
        imagePullPolicy: Never  # Use local image
        ports:
        - containerPort: 3000
        env:
        - name: REDIS_HOST
          value: "redis"
        - name: REDIS_PORT
          value: "6379"
---
apiVersion: v1
kind: Service
metadata:
  name: api
spec:
  type: LoadBalancer  # Use NodePort if LoadBalancer isn’t supported
  ports:
  - port: 3000
    targetPort: 3000
  selector:
    app: code-execution-api