apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: api-scaler
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["list"]  # For getQueueStatus
- apiGroups: ["apps"]
  resources: ["deployments", "deployments/scale"]
  verbs: ["get", "list", "patch"]  # For scaleWorkers
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: api-scaler-binding
subjects:
- kind: ServiceAccount
  name: default
  namespace: default
roleRef:
  kind: ClusterRole
  name: api-scaler
  apiGroup: rbac.authorization.k8s.io