apiVersion: apps/v1
kind: Deployment
metadata:
  name: webhook
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webhook
  template:
    metadata:
      labels:
        app: webhook
    spec:
      containers:
      - name: webhook
        image: code-execution-webhook:latest
        imagePullPolicy: Never  # Use local image
        ports:
        - containerPort: 3001
---
apiVersion: v1
kind: Service
metadata:
  name: webhook
spec:
  ports:
  - port: 3001
    targetPort: 3001
  selector:
    app: webhook